//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string Publisher { get; set; }
        public string Annotations { get; set; }
        public string Category { get; set; }
    }
}
